### ISSUE TITLE
GCE Login Token Persist Issue

### ISSUE THREAD

**Issue by Ginja** [hashicorp/vault-plugin-auth-gcp#83]
I've come across the following error when I was debugging a 400 HTTP return from some of our Vault clients. 

```
["error performing token check: failed to persist lease entry: cannot write to readonly storage"]
```

I've narrowed it down to when a client attempts to use their token shortly after a GCP login, but I'm not 100% certain on the cause. My guess is that it may be related to the issue that this [PR](https://github.com/hashicorp/vault/pull/8105) fixes, and/or that we're hitting some sort of race condition between using the token and performance standby WAL syncing.

Other facts on this issue and our setup:

* We're using Vault enterprise 1.3.2
* All of our standby nodes are performance standbys
* We're using the Raft storage backend
* Our clients are using the [Vault Ruby gem](https://github.com/hashicorp/vault-ruby)
* One workaround to this problem is to configure calls to Vault with re-attempts (a 400 still happens, but subsequent calls are successful)
* Introducing a delay after GCE authentication (e.g. `sleep 1`) fixes the issue (even without re-attempts)

**Comment by Ikana** [comment]
I'm seeing the same issue, running inside EKS and using `node-vault-client`. We also use vault enterprise.

**Comment by mliang2** [comment]
Also having this issue w/ approle auth using the vault cli.  I've determine this error occurs if you do a read immediately after auth.  This error only occurs if the request is made to a standby raft node.

The closer the client is to the server, the more likely the error.  I've tested it w/ a localhost raft cluster and the error occurs 4 out of 5 times.   Testing against a AWS cluster, w/ a ping time of 90ms, and the error doesn't occur at all.

**Comment by petems** [comment]
This isn't a plugin issue, it was a bug with Vault itself, and was fixed in Vault Enterprise 1.5.4

[Changelog entry:](https://github.com/hashicorp/vault/blob/master/CHANGELOG.md#154)

* replication (enterprise): Improve race condition when using a newly created token on a performance standby node

**Comment by bernardogza** [comment]
Is there any solution for this. I am having the same issue on 1.5.5+ prem

**Comment by petems** [comment]
@bernardogza I'd open a support ticket if it's affecting you on 1.5.5 Enterprise, as it should've been fixed in 1.5.4 Ent

**Comment by Ginja** [comment]
Can confirm we're still seeing this with 1.7.0 Enterprise. I'll raise it through the appropriate channels.

**Comment by EhsaanArk** [comment]
hey, guys any update on this issue? we cannot launch our product because of this pathetic issue!

**Comment by calvn** [comment]
@ncabatoff I have a feeling that the introduction of CCC (Client Controlled Consistency) in 1.7 may have addressed this. Is this correct?

@EhsaanArk if you're on 1.7 Enterprise or newer, can you give any of the consistency [mitigation suggestions](https://www.vaultproject.io/docs/enterprise/consistency#vault-1-7-mitigations) a try if you haven't already?

**Comment by ncabatoff** [comment]
> I have a feeling that the introduction of CCC (Client Controlled Consistency) in 1.7 may have addressed this. Is this correct?

We provide some additional mitigations as you referenced in the docs, correct.

**Comment by calvn** [comment]
We're going to go ahead and close this since haven't heard back from you in a while. Feel free to re-open if the above mitigation suggestions didn't end up helping with the issue.

**Comment by Maghil** [comment]
I am using vault enterprise 1.7.3+ and facing this exact issue when I try to run my python testcases with pytest fixtures
I am using this functions to get my secrets and pass them as fixtures
I couldn't understand what the error means

> does this mean we can't write secrets we retrieved from vault into a text file? pytest fixtures is only trying to save the retrieved secrets and not authorized client object So I am out of clue

**BTW I can't change my enterprise vault server configuration**

```from attr import validate
import pytest
import hvac
import os
from os import path`

mount_point = "foo"

def vaultAuth():
    """function to authenticate user with vault"""
    try:
        client = hvac.Client(url="xxxxxx")
        client.auth.github.login(token=os.getenv("ACCESS_TOKEN"), mount_point=mount_point)
        return(client)
    except Exception as e:
        print(e)

@pytest.fixture(scope="session")
def envCreds():
    """funciton to retrieve environment specific creds"""
    environment = ["qa", "prod"]
    env = os.getenv("ENVIRONMENT")
    if env:
        if env in environment:
            secret_path = <path>+env
            read_secret_result = vaultAuth().read(secret_path)
            return(read_secret_result['data'])
        else:
            raise ValueError("wrong environment given")
    else:
        raise ValueError("there is no key called ENVIRONMENT")```
        
when I execute using pytest I am getting
```creds.py:31: in envCreds
    read_secret_result = vaultAuth().read(secret_path)
.tox/py38/lib/python3.8/site-packages/hvac/v1/__init__.py:236: in read
    return self._adapter.get("/v1/{0}".format(path), wrap_ttl=wrap_ttl)
.tox/py38/lib/python3.8/site-packages/hvac/adapters.py:108: in get
    return self.request("get", url, **kwargs)
.tox/py38/lib/python3.8/site-packages/hvac/adapters.py:356: in request
    response = super(JSONAdapter, self).request(*args, **kwargs)
.tox/py38/lib/python3.8/site-packages/hvac/adapters.py:322: in request
    utils.raise_for_error(
.tox/py38/lib/python3.8/site-packages/hvac/utils.py:37: in raise_for_error
    raise exceptions.InvalidRequest(message, errors=errors, method=method, url=url)
E   hvac.exceptions.InvalidRequest: error performing token check: failed to persist lease entry: cannot write to readonly storage, on get h<url>```
